import type { NextPage } from "next";
import Head from "next/head";
import FilmCard from "../components/FilmCard";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import Skeleton from "../components/Skeleton";
import Footer from "../components/Footer";
import { Film } from "../interfaces/film.interface";

const Home: NextPage = ({ films }: any) => {
  return (
    <>
      <Header page="" />

      <div className={styles.container}>
        <Head>
          <title>Haftanın Kısa Filmi - Next</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.filmCardContainer}>
          {(() => {
            if (!films) {
              return (
                <>
                  {[...Array(30)].map((x, i) => (
                    <Skeleton key={i} type="listPage" />
                  ))}
                </>
              );
            } else {
              return (
                <>
                  {films.map((film: Film) => (
                    <FilmCard key={film.link} film={film} />
                  ))}
                </>
              );
            }
          })()}
        </div>
      </div>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  console.log("env", process.env.VERCEL_ENV);
  console.log("url", process.env.VERCEL_URL);

  let url: string;
  if (process.env.VERCEL_ENV === "development") {
    url = "http://localhost:3000/api/all?page=1&sortBy=latest&perPage=10000";
  } else {
    url = `https://${process.env.VERCEL_URL}/api/all?page=1&sortBy=latest&perPage=10000`;
  }
  const res = await fetch(url);
  const data = await res.json();
  const films = data.data;

  return {
    props: {
      films,
    },
  };
}

export default Home;
