import type { NextPage } from "next";
import Head from "next/head";
import FilmCard from "../components/FilmCard";
import styles from "../styles/Home.module.scss";
import useSWR from "swr";
import fetcher from "../lib/fetcher";
import Header from "../components/Header";
import Skeleton from "../components/Skeleton";
import { FilmsResponse } from "../interfaces/films-response.interface";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  const { data, error } = useSWR<FilmsResponse>(
    "/api/all?page=1&sortBy=latest&perPage=10000",
    fetcher
  );

  if (error) return <div>failed to load</div>;

  return (
    <>
      <Header page="" />

      <div className={styles.container}>
        <Head>
          <title>Haftanın Kısa Filmi - Next</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.filmCardContainer}>
          {(() => {
            if (!data) {
              return (
                <>
                  {[...Array(30)].map((x, i) => (
                    <Skeleton key={i} type="listPage" />
                  ))}
                </>
              );
            } else {
              return (
                <>
                  {data.data.map((film) => (
                    <FilmCard key={film.link} film={film} />
                  ))}
                </>
              );
            }
          })()}
        </div>
      </div>

      <Footer />
    </>
  );
};

export default Home;
